base_url = "https://assorion.moyai.shop/"
compile_sass = false

build_search_index = true

theme = "anemone"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = true

[extra]
favicon = "favicon.ico"
image = ""
default_theme = "dark"
header_nav = [
  { url = "/",           name_en = "/main/"},
  { url = "/changelog",  name_en = "/changelog/"},
  { url = "/modding",    name_en = "/modding/"},
  { url = "/philosophy", name_en = "/philosophy/"},
  { url = "/discord.html",    name_en = "/discord/"}
]

twitter_card = false
