base_url = "https://assorion.github.io/wiki/"
compile_sass = false
favicon = "favicon.ico"

build_search_index = true

theme = "anemone"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = true

[extra]
default_theme = "dark"
header_nav = [
  { url = "/wiki",           name_en = "/main/"},
  { url = "/wiki/changelog",  name_en = "/changelog/"},
  { url = "/wiki/modding",    name_en = "/modding/"},
  { url = "/wiki/philosophy", name_en = "/philosophy/"},
  { url = "/wiki/discord.html",    name_en = "/discord/"}
]

twitter_card = false
