name: Assorion Website Deploy

env:
  ZOLA_VERSION: "0.15.3"
  SOURCE_BRANCH: "main"
  TARGET_BRANCH: "gh-pages"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      issues: write
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install zola
      run: |
        set -x
        wget -O - \
           "https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz" \
        | sudo tar xzf - -C /usr/local/bin
    - name: Generate HTML
      run: zola build
    - name: Deploy to gh-pages
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages 
        FOLDER: .
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        MESSAGE: "Build: ({sha}) {msg}" # The commit messag
